# Generated by Django 6.0.7 on 2026-07-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_image',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_price',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
    ]
