# Generated by Django 6.0.7 on 2026-08-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0009_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
